/**
 * Deterministic regression-test scaffolding for TESTS findings. Generated
 * tests are templates derived from the real route/function under change —
 * never executed automatically, never applied without explicit user action.
 */
import type { Finding } from "../types";

function inferHandlerImport(file: string): { importPath: string; handler: string } {
  const importPath = file.replace(/\.(ts|tsx|js|jsx)$/, "").replace(/^src\//, "../src/");
  const fnMatch = /[\w/-]+$/.exec(importPath);
  return { importPath, handler: fnMatch?.[0]?.split("/").pop() ?? "handler" };
}

export function generateRouteTest(finding: Finding): { filename: string; content: string } | null {
  const isRoute = /endpoint|route|POST|GET|PUT|PATCH|DELETE/i.test(finding.title) || finding.evidence.some((e) => /endpoint|POST |GET /.test(e.detail));
  const stem = finding.file.split("/").pop()!.replace(/\.[a-z]+$/, "");
  const { importPath } = inferHandlerImport(finding.file);
  const routeName = finding.title.replace(/^No tests cover /, "").trim();

  if (isRoute) {
    const content = `// Generated by PRISM for: ${finding.title}
// SCAFFOLD: replace \`request(app)\` wiring with your app's test harness and
// fill in fixtures. PRISM never applies this without explicit user action.
import { describe, it, expect } from "vitest";
// import request from "supertest";
// import { app } from "${importPath.replace(/\.\.\/src\/.*/, "../src/app")}";

describe("${routeName}", () => {
  it("rejects unauthenticated requests with 401", async () => {
    // TODO: issue request WITHOUT credentials
    // const res = await request(app).post("${routeName.includes(" ") ? routeName.split(" ").slice(1).join(" ") : "/route"}").send({});
    // expect(res.status).toBe(401);
    expect(true).toBe(true);
  });

  it("rejects authenticated callers without the required role (403)", async () => {
    // TODO: authenticate as a low-privilege member, assert 403.
  });

  it("rejects malformed / missing body fields with 400", async () => {
    // TODO: POST {} and malformed types; assert field-level errors.
  });

  it("returns 404 for a target that does not exist (never 500)", async () => {
    // TODO: random/non-existent id must map to a handled 404.
  });

  it("does not create duplicates on repeated submission", async () => {
    // TODO: send the same valid payload twice; assert one record / 409.
  });

  it("succeeds for an authorized caller and returns the documented shape", async () => {
    // TODO: happy path; assert status and response contract fields.
  });
});
`;
    return { filename: `${stem}.prism.test.ts`, content };
  }

  const content = `// Generated by PRISM for: ${finding.title}
import { describe, it, expect } from "vitest";
// import { ${inferHandlerImport(finding.file).handler} } from "${importPath}";

describe("${finding.title.replace(/^No tests cover /, "")}", () => {
  it("handles null / undefined input without throwing", async () => {
    // TODO: assert a handled error / empty result.
  });
  it("handles empty collection and boundary values", async () => {
    // TODO: zero, one, and exactly-at-limit inputs.
  });
  it("treats repeated input idempotently", async () => {
    // TODO: duplicate submission produces no duplicate effects.
  });
  it("happy path returns expected result", async () => {
    // TODO: valid input -> asserted result.
  });
});
`;
  return { filename: `${stem}.prism.test.ts`, content };
}
